// <auto-generated />
using System;
using FuelPriceWizard.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelPriceWizard.DataAccess.Migrations
{
    [DbContext(typeof(FuelPriceWizardDbContext))]
    [Migration("20241129194537_FixCurrencyPriceReadingRelation")]
    partial class FixCurrencyPriceReadingRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.Base.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Symbol");

                    b.HasKey("Id")
                        .HasName("PK_CurrencyId");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.Base.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Abbreviation");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DisplayValue");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.HasKey("Id")
                        .HasName("PK_FuelTypeId");

                    b.ToTable("FuelTypes", (string)null);
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.Base.GasStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Designation");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_GasStationId");

                    b.ToTable("GasStations", (string)null);
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.PriceReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FetchedAt");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GasStationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("Value");

                    b.HasKey("Id")
                        .HasName("PK_PriceReadingId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GasStationId");

                    b.ToTable("PriceReadings", (string)null);
                });

            modelBuilder.Entity("FuelTypeGasStation", b =>
                {
                    b.Property<int>("FuelTypesId")
                        .HasColumnType("int");

                    b.Property<int>("GasStationsId")
                        .HasColumnType("int");

                    b.HasKey("FuelTypesId", "GasStationsId");

                    b.HasIndex("GasStationsId");

                    b.ToTable("FuelTypeGasStation");
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.PriceReading", b =>
                {
                    b.HasOne("FuelPriceWizard.DataAccess.Entities.Base.Currency", "Currency")
                        .WithMany("PriceReadings")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelPriceWizard.DataAccess.Entities.Base.FuelType", "FuelType")
                        .WithMany("PriceReadings")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelPriceWizard.DataAccess.Entities.Base.GasStation", "GasStation")
                        .WithMany("PriceReadings")
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("FuelType");

                    b.Navigation("GasStation");
                });

            modelBuilder.Entity("FuelTypeGasStation", b =>
                {
                    b.HasOne("FuelPriceWizard.DataAccess.Entities.Base.FuelType", null)
                        .WithMany()
                        .HasForeignKey("FuelTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelPriceWizard.DataAccess.Entities.Base.GasStation", null)
                        .WithMany()
                        .HasForeignKey("GasStationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.Base.Currency", b =>
                {
                    b.Navigation("PriceReadings");
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.Base.FuelType", b =>
                {
                    b.Navigation("PriceReadings");
                });

            modelBuilder.Entity("FuelPriceWizard.DataAccess.Entities.Base.GasStation", b =>
                {
                    b.Navigation("PriceReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
