name: Angular

on:
  push:
    branches:
      - main
    paths:
      - "FuelPriceWizard.UI/**"
  pull_request:
    branches:
      - main
    paths:
      - "FuelPriceWizard.UI/**"

env:
  NODE_VERSION: '22.8.x'

defaults:
  run:
    working-directory: FuelPriceWizard.UI/fuelpricewizard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Lint Angular code
        run: npm run lint

      - name: Build Angular project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run Angular tests with coverage
        run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: coverage/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: angular-test-results
          path: FuelPriceWizard.UI/fuelpricewizard/test-results/
