# This workflow will build, test and deploy the .NET projects

name: .NET

on:
  push:
    branches: ["main"]
    paths:
      - "FuelPriceWizard.API/**"
      - "FuelPriceWizard.BusinessLogic/**"
      - "FuelPriceWizard.DataAccess/**"
      - "FuelPriceWizard.DataCollector/**"
      - "FuelPriceWizard.Domain/**"
      - "**CollectorService"
  pull_request:
    branches: ["main"]
    paths:
      - "FuelPriceWizard.API/**"
      - "FuelPriceWizard.BusinessLogic/**"
      - "FuelPriceWizard.DataAccess/**"
      - "FuelPriceWizard.DataCollector/**"
      - "FuelPriceWizard.Domain/**"
      - "**CollectorService"

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run tests
        run: dotnet test -c Release --no-build